name: tubecards
description: Spaced Repetition for flashcards with YouTube
# The version and build number according to semver.org
version: 2.1.0+88
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 3.3.4

dependencies:
  adaptive_theme: ^3.1.1
  amplitude_flutter: ^3.7.0
  android_intent_plus: ^3.0.0
  app_links: ^3.2.0
  app_settings: ^4.1.0
  archive: ^3.1.2
  auto_size_text: ^3.0.0-nullsafety.0
  bitsdojo_window: ^0.1.5
  built_collection: ^5.0.0
  built_value: ^8.0.4
  cached_network_image: ^3.2.1
  clock: ^1.1.0
  collection: ^1.15.0
  confetti: 0.7.0
  copy_with_extension: ^4.0.2
  crypto: ^3.0.0
  csv: ^5.0.0
  delta_markdown: ^0.8.0
  devicelocale: ^0.5.0
  dio: ^4.0.0-prev3
  email_validator: ^2.0.1
  envify:
    git:
        url: https://github.com/techouse/envify.git
        ref: main
        path: envify
  equatable: ^2.0.0
  extended_image: ^6.2.1
  ferry: ^0.11.2+1
  ferry_generator: ^0.6.1
  ferry_hive_store: ^0.4.5
  file: ^6.1.2
  file_picker: ^5.2.1
  file_selector: ^0.9.2+1
  file_selector_linux: ^0.9.0+1
  file_selector_macos: ^0.9.0+3
  file_selector_windows: ^0.9.1+4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0-nullsafety.2
  flutter_colorpicker: ^1.0.3
  flutter_isolate: ^2.0.1-pre
  flutter_local_notifications: ^12.0.2
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.1
  flutter_markdown: ^0.6.12
  flutter_native_timezone: ^2.0.0
  flutter_painter: ^1.0.1
  flutter_phosphor_icons: ^0.0.1+5
  flutter_quill: ^6.0.8+1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.0
  flutter_tts: ^3.0.0
  font_awesome_flutter: ^10.0.0
  get_it: ^7.0.0
  gql_error_link: ^0.2.3
  gql_exec: ^0.4.1
  gql_http_link: ^0.4.4+1
  gql_transform_link: ^0.2.2
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  html2md: ^1.2.4
  http: ^0.13.1
  # To support SVG images on Android
  image_picker:
    git:
      url: https://github.com/friebetill/plugins
      ref: 996b6dd
      path: packages/image_picker/image_picker
  in_app_review: ^2.0.3
  injectable: ^1.2.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  lazy_load_scrollview: ^1.3.0
  logging: ^1.0.0
  mailer: ^5.0.0
  markdown: ^6.0.1
  meta: ^1.3.0
  msix: ^3.6.2
  notification_permissions: ^0.6.1
  package_info_plus: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  percent_indicator: ^4.2.2
  # Don't update until this issue is resolved, https://bit.ly/3q42eSD
  purchases_flutter: ^3.9.5
  quiver: ^3.0.0
  recase: ^4.0.0-nullsafety.0
  retry: ^3.1.0
  rxdart: ^0.27.1
  sentry_flutter: ^6.9.0
  share_plus: ^4.0.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  sliver_tools: ^0.2.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  step_progress_indicator: ^1.0.1
  sticky_headers: ^0.3.0+2
  streaming_shared_preferences: ^2.0.0
  timelines: ^0.1.0
  timezone: ^0.9.0
  tuple: ^2.0.0
  uni_links: 0.5.1
  url_launcher: ^6.0.2
  uuid: ^3.0.2
  video_player: ^2.0.2
  visibility_detector: ^0.3.3

dev_dependencies:
  build_runner: ^2.0.6
  copy_with_extension_gen: ^4.0.2
  envify_generator: # ^2.0.2
      git:
        url: https://github.com/techouse/envify.git
        ref: main
        path: envify_generator
  # This currently often crashes the analyzer.
  # dart_code_metrics: ^4.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter
  # Waiting for this PR https://bit.ly/3tO37NG
  gen_lang:
    git:
      url: https://github.com/KingWu/gen_lang
      ref: 7ba7548
  golden_toolkit: ^0.13.0
  injectable_generator: ^1.2.2
  json_serializable: ^6.0.0
  json_serializable_immutable_collections: ^0.10.0
  # Waiting for this PR https://bit.ly/31jtfUJ
  lang_table:
    git:
      url: https://github.com/KingWu/lang_table
      ref: 9f127d6
  test: ^1.19.5

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/ic_launcher_xxxhdpi.png
  image_path_ios: assets/icon/ios.png
  adaptive_icon_background: assets/icon/ic_background.png
  adaptive_icon_foreground: assets/icon/ic_foreground.png

dependency_overrides:
  envify_generator: # ^2.0.2
    git:
      url: https://github.com/techouse/envify.git
      ref: main
      path: envify_generator
  i18n_extension:
    git:
      url: https://github.com/ndungudedan/i18n_extension
  image_picker:
    git:
      url: https://github.com/friebetill/plugins
      ref: 996b6dd
      path: packages/image_picker/image_picker

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/videos/
  fonts:
    - family: SanFranciscoPro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
    - family: SanFranciscoMono
      fonts:
        - asset: assets/fonts/SF-Mono-Regular.otf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: OSIcons
      fonts:
        - asset: assets/fonts/OSIcons.ttf

# To create a new splash screen: flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splash_screen_dark.png
  # Primary color of the dark mode
  color: "#121212"

msix_config:
  publisher_display_name: TubeCards App
  identity_name: 32902SpaceApp.SpaceSpacedRepetition
  display_name: "TubeCards: Spaced Repetition"
  msix_version: 2.1.0.0
  store: true
  publisher: CN=902234FE-40EF-4B23-8724-83780B4C06BE
  capabilities: "internetClient"
  icons_background_color: transparent
  logo_path: windows/runner/resources/app_icon.png
  start_menu_icon_path: windows/runner/resources/app_icon.png
  tile_icon_path: windows/runner/resources/app_icon.png
